In [2]:
import pandas as pd
import json

In [3]:
df = pd.read_csv('/Users/parlorsky/Downloads/v3_vacancies_type_id (1).csv')

In [4]:
first25 = [16, 27, 31, 33, 49, 52, 54, 58, 61, 69, 74, 91, 116, 119, 128, 134, 283, 336, 663, 706, 767, 783, 833, 836, 919]
second25 = [43, 23, 84, 85, 87, 124, 357, 561, 693, 712, 742, 765, 811, 812, 852, 853, 856, 873, 876, 888, 898, 917, 921, 954, 992]
third25 = [2, 35, 40, 86, 102, 111, 320, 324, 325, 326, 337, 698, 720, 734, 760, 804, 829, 850, 904, 941, 982, 994, 996, 997, 998]

In [7]:
bundels = first25 + second25 + third25

In [8]:
df = df[df['vacancies_type_id'].isin(bundels)][['vacancies_type_id','vacancies_type_name']]

In [9]:
df

     vacancies_type_id                                vacancies_type_name
2                    2                                  Ветеринарный врач
16                  16                              Оператор станка с ЧПУ
23                  23  Рабочий отделочных строительных и декоративных...
27                  27                                             Токарь
31                  31                                        Фрезеровщик
..                 ...                                                ...
772                992                                Машинист бульдозера
774                994                              Машинист автогрейдера
776                996                            Машинист трубоукладчика
777                997                        Машинист крана  / Крановщик
778                998           Машинист автовышки и автогидроподъемника

[75 rows x 2 columns]

In [10]:
di = dict()

In [18]:
for i,j in zip(df['vacancies_type_id'],df['vacancies_type_name']):
    print(f'{i}_{j}')

2_Ветеринарный врач
16_Оператор станка с ЧПУ
23_Рабочий отделочных строительных и декоративных работ / Отделочник / Штукатур
27_Токарь
31_Фрезеровщик
33_Бармен / Официант / Бариста
35_Ветеринарный фельдшер
40_Мастер общестроительных работ
43_Повар
49_Офис-менеджер
52_Стропальщик
54_Специалист по охране труда
58_Администратор магазина
61_Инженер-геодезист/Геодезист
69_Массажист
74_Секретарь
84_Шлифовщик
85_Экономист
86_Агроном
87_Администратор салона красоты
91_Библиотекарь
102_Зоотехник
111_Менеджер по логистике
116_Оператор ПК
119_Плиточник
124_Руководитель библиотеки
128_Специалист по социальной работе
134_Медицинский представитель
283_Врач-стоматолог
320_Инженер по организации эксплуатации, ремонту и обслуживанию оборудования/систем/сетей
324_Инженер-конструктор
325_Инженер-проектировщик
326_Инженер-технолог
336_Автомеханик / Автослесарь
337_Агент страховой
357_Сантехник
561_Радиотехник/Техник по обслуживанию радио-электрооборудования
663_Автоэлектрик
693_Картограф
698_Контролер качества технический (ОТК)
706_Маляр
712_Монтер пути
720_Оператор-наладчик
734_Риэлтор / Специалист по недвижимости
742_Составитель поездов
760_Формовщик
765_Электрик
767_Администратор медицинского центра
783_Личный помощник руководителя
804_Животновод
811_Монтажник систем вентиляции и кондиционирования воздуха
812_Машинист ЖД / Метро
829_Оператор искусственного осеменения
833_Дефектоскопист (Инженер-дефектоскопист)
836_Бетонщик / Арматурщик / Монолитчик
850_Инженер-механик
852_Руководитель организации социального обслуживания
853_Социальный работник
856_Слесарь-сантехник
873_Инженер-радиотехник
876_Сигналист
888_Электрослесарь / Слесарь- электрик
898_Инженер по сварке
904_Слесарь по сборке металлоконструкций
917_Водитель трамвая
919_Водитель автобуса
921_Монтажник санитарно-технических систем и оборудования
941_Рабочий зеленого хозяйства
954_Наладчик сварочного оборудования
982_Контролер станочных и слесарных работ
992_Машинист бульдозера
994_Машинист автогрейдера
996_Машинист трубоукладчика
997_Машинист крана  / Крановщик
998_Машинист автовышки и автогидроподъемника

In [16]:
with open('professions.json','w') as f:
    json.dump(di,f,indent =4 ,ensure_ascii=True)